### ISSUE TITLE
Semantic-release

### ISSUE THREAD

**Issue by gajus** [conventional-commits/conventional-commits-action#1]
In case you are not familiar, there is a well adopted project:

https://github.com/semantic-release/semantic-release

**Comment by hutson** [comment]
cc @pvdlg @bcoe 

I wonder if a GitHub action would be a good alternative to a dedicated GitHub App? (I know `semantic-release` has been looking into supporting an App at some point - semantic-release/semantic-release/issues/585).

I too was planning on supporting an App for automated releases, but I just wrote a [Docker image that supports automated deliverables from a GitHub Action](https://gitlab.com/hyper-expanse/open-source/docker/semantic-release-github#github-action).

**Comment by bcoe** [comment]
@gajus @hbetts completely aware, just playing around with actions a bit using the `standard-version` library which I wrote.

_my goal being to play around a bit with npm workflows and GitHub actions, I bet the semantic-release folks will eventually release a fully featured action._
